name: release
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - run: corepack enable
      - run: yarn --version
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: Install
        run: yarn install --frozen-lockfile --prefer-offline
      - name: Release
        run: npx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
